In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import metrics
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
import datetime as dt
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from mlxtend.plotting import plot_learning_curves
from mlxtend.plotting import plot_decision_regions
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb
from sklearn.ensemble import StackingClassifier
from sklearn.decomposition import PCA

In [2]:
file = 'use_of_force_model_data.csv'
data = pd.read_csv(file, index_col = 0)
data

,datetime,Incident Location: Street/Highway,Incident Location: Public Transport,Incident Location: Retail Premises,"Incident Location: Open ground (e.g. park, car park, field)",Incident Location: Licensed Premises,Incident Location: Sports or Event Stadia,Incident Location: Hospital/A&E (non-mental-health setting),Incident Location: Mental Health Setting,Incident Location: Police vehicle with prisoner handling cage,...,Newham,Out of force,Redbridge,Richmond upon Thames,Southwark,Sutton,Tower Hamlets,Waltham Forest,Wandsworth,is force required?
0,2020-04-01 00:12:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2020-04-01 01:30:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,2020-04-01 03:30:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,2020-04-01 04:25:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,2020-04-01 04:12:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147890,2021-01-31 18:00:00,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
147891,2021-01-31 15:20:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147892,2021-01-31 22:00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
147893,2021-01-31 19:48:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
147894,2021-01-31 19:20:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
data.drop(columns = 'datetime', inplace = True)

In [4]:
data.head()

,Incident Location: Street/Highway,Incident Location: Public Transport,Incident Location: Retail Premises,"Incident Location: Open ground (e.g. park, car park, field)",Incident Location: Licensed Premises,Incident Location: Sports or Event Stadia,Incident Location: Hospital/A&E (non-mental-health setting),Incident Location: Mental Health Setting,Incident Location: Police vehicle with prisoner handling cage,Incident Location: Police vehicle without prisoner handling cage,...,Newham,Out of force,Redbridge,Richmond upon Thames,Southwark,Sutton,Tower Hamlets,Waltham Forest,Wandsworth,is force required?
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [5]:
data_small = data.sample(20000, random_state = 7)

In [8]:
for i in data_small.columns:
    print(data_small[i].value_counts())

1    11564
0     8436
Name: Incident Location: Street/Highway, dtype: int64
0    19801
1      199
Name: Incident Location: Public Transport, dtype: int64
0    19611
1      389
Name: Incident Location: Retail Premises, dtype: int64
0    19208
1      792
Name: Incident Location: Open ground (e.g. park, car park, field), dtype: int64
0    19948
1       52
Name: Incident Location: Licensed Premises, dtype: int64
0    19994
1        6
Name: Incident Location: Sports or Event Stadia, dtype: int64
0    19625
1      375
Name: Incident Location: Hospital/A&E (non-mental-health setting), dtype: int64
0    19915
1       85
Name: Incident Location: Mental Health Setting, dtype: int64
0    19959
1       41
Name: Incident Location: Police vehicle with prisoner handling cage, dtype: int64
0    19966
1       34
Name: Incident Location: Police vehicle without prisoner handling cage, dtype: int64
0    15832
1     4168
Name: Incident Location: Dwelling, dtype: int64
0    19619
1      381
Name: Incident Location: Police station (excluding custody block), dtype: int64
0    18759
1     1241
Name: Incident Location: Custody Block, dtype: int64
0    19945
1       55
Name: Incident Location: Ambulance, dtype: int64
0    19382
1      618
Name: Incident Location: Other, dtype: int64
0    19960
1       40
Name: MainDuty: AFO, dtype: int64
0    19479
1      521
Name: MainDuty: ARV, dtype: int64
0    19812
1      188
Name: MainDuty: CID, dtype: int64
0    19954
1       46
Name: MainDuty: CTSFO, dtype: int64
0    19189
1      811
Name: MainDuty: Custody, dtype: int64
0    19927
1       73
Name: MainDuty: Dog handler duty, dtype: int64
0    18772
1     1228
Name: MainDuty: Foot patrol, dtype: int64
1    15159
0     4841
Name: MainDuty: Mobile patrol, dtype: int64
0    19996
1        4
Name: MainDuty: Mounted section duties, dtype: int64
0    19955
1       45
Name: MainDuty: Off duty, dtype: int64
0    19050
1      950
Name: MainDuty: Other, dtype: int64
0    19560
1      440
Name: MainDuty: PSU/Public order, dtype: int64
0    19529
1      471
Name: MainDuty: Roads policing, dtype: int64
0    19976
1       24
Name: MainDuty: Surveillance, dtype: int64
0    19528
1      472
Name: SingleCrewed, dtype: int64
3.0    11476
4.0     4900
2.0     2094
5.0     1412
6.0      118
Name: SubjectAge, dtype: int64
0    19779
1      221
Name: PhysicalDisability, dtype: int64
0    17150
1     2850
Name: MentalDisability, dtype: int64
0    17599
1     2401
Name: SubjectGender: Female, dtype: int64
1    17529
0     2471
Name: SubjectGender: Male, dtype: int64
0    19930
1       70
Name: SubjectGender: Other, dtype: int64
0    17369
1     2631
Name: SubjectEthnicity: Asian, dtype: int64
0    12692
1     7308
Name: SubjectEthnicity: Black, dtype: int64
0    19894
1      106
Name: SubjectEthnicity: Chinese, dtype: int64
0    19776
1      224
Name: SubjectEthnicity: Unknown, dtype: int64
0    19299
1      701
Name: SubjectEthnicity: Mixed, dtype: int64
0    19137
1      863
Name: SubjectEthnicity: Other, dtype: int64
0    11833
1     8167
Name: SubjectEthnicity: White, dtype: int64
0    19439
1      561
Name: Barking and Dagenham, dtype: int64
0    19439
1      561
Name: Barnet, dtype: int64
0    19570
1      430
Name: Bexley, dtype: int64
0    19119
1      881
Name: Brent, dtype: int64
0    19478
1      522
Name: Bromley, dtype: int64
0    19253
1      747
Name: Camden, dtype: int64
0    18559
1     1441
Name: City of Westminster, dtype: int64
0    19064
1      936
Name: Croydon, dtype: int64
0    19373
1      627
Name: Ealing, dtype: int64
0    19481
1      519
Name: Enfield, dtype: int64
0    19356
1      644
Name: Greenwich, dtype: int64
0    19197
1      803
Name: Hackney, dtype: int64
0    19468
1      532
Name: Hammersmith and Fulham, dtype: int64
0    19317
1      683
Name: Haringey, dtype: int64
0    19674
1      326
Name: Harrow, dtype: int64
0    19523
1      477
Name: Havering, dtype: int64
0    19899
1      101
Name: Heathrow, dtype: int64
0    19448
1      552
Name: Hillingdon, dtype: int64
0    19531
1      469
Name: Hounslow, dtype: int64
0    19436
1      564
Name: Islington, dtype: int64
0    19670
1      330
Name: Kensington and Chelsea, dtype: int64
0    19659
1      341
Name: Kingston upon Thames, dtype: int64
0    19073
1      927
Name: Lambeth, dtype: int64
0    19146
1      854
Name: Lewisham, dtype: int64
0    19747
1      253
Name: Merton, dtype: int64
0    19046
1      954
Name: Newham, dtype: int64
0    19839
1      161
Name: Out of force, dtype: int64
0    19535
1      465
Name: Redbridge, dtype: int64
0    19809
1      191
Name: Richmond upon Thames, dtype: int64
0    19082
1      918
Name: Southwark, dtype: int64
0    19727
1      273
Name: Sutton, dtype: int64
0    19120
1      880
Name: Tower Hamlets, dtype: int64
0    19462
1      538
Name: Waltham Forest, dtype: int64
0    19461
1      539
Name: Wandsworth, dtype: int64
0    10777
1     9223
Name: is force required?, dtype: int64

# Set Baseline Target Result

In [10]:
data_small['is force required?'].value_counts()

0    10777
1     9223
Name: is force required?, dtype: int64

Our baseline target accuracy to beat is 46%.

# Assign Input and Output Variables

In [11]:
X = data_small.iloc[:, :-1]
y = data_small.iloc[:, -1]

In [15]:
X.shape

(20000, 77)

# Dimensionality Reduction (PCA)

In [14]:
pca = PCA(n_components = 20)
pca.fit(X)

PCA(n_components=20)

In [16]:
X_pca = pca.transform(X)

In [17]:
X_pca.shape

(20000, 20)

# Split Data

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, random_state = 7, test_size = 0.2)

# Create Baseline Models

In [23]:
# Evaluation Model
baseline_score = {}
def evaluate_model(model, X_test, y_test, model_name):
    preds = model.predict(X_test)
    plt.figure()
    plot_learning_curves(X_train, y_train, X_test, y_test, model, print_model = False, style = 'ggplot')
    plt.title(f'{model_name} Learning Curve')
    plt.show()
    print(f'Model: {model_name}' )
    print('Model score:', round(model.score(X_test, y_test),2))
    print('----------------------------------------------------------')
    print('Classification Report:\n')
    print(metrics.classification_report(y_test, preds))
    baseline_score[model_name] = round(model.score(X_test, y_test),3)
    print('----------------------------------------------------------')
    print('Baseline Scores List')
    print(baseline_score)

# Evaluation bagging
bagging_score = {}
def evaluate_bagger(model, X_test, y_test, model_name):
    preds = model.predict(X_test)
    plt.figure()
    plot_learning_curves(X_train, y_train, X_test, y_test, model, print_model = False, style = 'ggplot')
    plt.title(f'{model_name} Learning Curve')
    plt.show()
    print(f'Model: {model_name}' )
    print('Model score:', round(model.score(X_test, y_test),2))
    print('----------------------------------------------------------')
    print('Classification Report:\n')
    print(metrics.classification_report(y_test, preds))
    bagging_score[model_name] = round(model.score(X_test, y_test),3)
    print('----------------------------------------------------------')
    print('Bagging Scores List')
    print(bagging_score)

In [20]:
# Parameter Searching

knn = KNeighborsClassifier()
params_knn = {'n_neighbors': np.arange(1, 25)}
knn_gs = GridSearchCV(knn, params_knn, cv = 5)
knn_gs.fit(X_train, y_train)
knn_best = knn_gs.best_estimator_
print(knn_best)

KNeighborsClassifier(n_neighbors=20)

In [22]:
dt = DecisionTreeClassifier()
params_dt = {'max_leaf_nodes': np.arange(2, 100)}
dt_gs = GridSearchCV(dt, params_dt, cv = 5)
dt_gs.fit(X_train, y_train)
dt_best = dt_gs.best_estimator_
print(dt_best)

DecisionTreeClassifier(max_leaf_nodes=33)

In [24]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

knn = KNeighborsClassifier(n_neighbors = 20)
knn.fit(X_train, y_train)

svc = SVC(probability = True)
svc.fit(X_train, y_train)

dt = DecisionTreeClasifier(max_leaf_nodes = 33)
dt.fit(X_train, y_train)

nb = BernoulliNB()
nb.fit(X_train, y_train)

random_forest = RandomForestClassifier(criterion='entropy', n_estimators= 100, max_features='auto', random_state=7)
random_forest.fit(X_train, y_train)

classifiers = [lr, knn, svc, dt, nb, random_forest]
classifier_names = ['Logistic Regression', 'KNN', 'SVC', 'Decision Tree', 'Bernoulli Naive Bayes', 'Random Forest']

NameError: name 'DecisionTreeClasifier' is not defined

In [ ]:
for model, name in zip(classifiers, classifier_names):
    evaluate_model(model, X_test, y_test, name)